version: 2
jobs:
  test:
    docker:
    - image: circleci/golang:1.10
    working_directory: /go/src/github.com/mumoshu/variant
    steps:
    - checkout
    - run: make smoke-ci
  release:
    docker:
    - image: circleci/golang:1.10
    working_directory: /go/src/github.com/mumoshu/variant
    steps:
    - checkout
    - run: curl -sL https://git.io/goreleaser | bash
workflows:
  version: 2
  build:
    jobs:
    - test
  release:
    jobs:
    - test:
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /v[0-9]+(\.[0-9]+)*(-.*)*/
    - release:
        requires:
        - test
        filters:
          branches:
            ignore: /.*/
          tags:
            only: /v[0-9]+(\.[0-9]+)*(-.*)*/
